const actionTypes = {
    LOAD_POKEMONS: "LOAD_POKEMONS",
    LOAD_POKEMONS_ERROR: "LOAD_POKEMONS_ERROR",
    INCREMENT_LOADING_COUNTER: "INCREMENT_LOADING_COUNTER",
    DECREMENT_LOADING_COUNTER: "DECREMENT_LOADING_COUNTER",
};

export default actionTypes;
